 
specification_path: "./specs/schemas"
emulator_url: "http://localhost:8080"
timeout: 10
output_path: "./reports"
 
auth:
  type: "basic"
  username: "admin"
  password: "admin"
 
resources_filter:
  - "StorageSystems"
  - "StoragePools"
  - "Volumes"
  - "Drives"
 